# Generated by Django 2.2.9 on 2020-01-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='code',
        ),
    ]
